# Generated by Django 4.0 on 2022-02-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('fb_link', models.URLField(max_length=255)),
                ('twitter_link', models.URLField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
